<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('libsimplequery')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_libsimplequery.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('libsimplequery.so')) return;
    } else {
      if (!dl('libsimplequery.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



/* PHP Proxy Classes */
class StrVector {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_libsimplequery_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_libsimplequery_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	public function __construct($n=null) {
		if (is_resource($n) && get_resource_type($n) === '_p_std__vectorT_std__string_t') {
			$this->_cPtr=$n;
			return;
		}
		$this->_cPtr=$r;
		switch (func_num_args()) {
		case 0: $this->_cPtr=new_StrVector(); break;
		default: $this->_cPtr=new_StrVector($n);
		}
	}

	public function size() {
		return StrVector_size($this->_cPtr);
	}

	public function capacity() {
		return StrVector_capacity($this->_cPtr);
	}

	public function reserve($n) {
		StrVector_reserve($this->_cPtr,$n);
	}

	public function clear() {
		StrVector_clear($this->_cPtr);
	}

	public function push($x) {
		StrVector_push($this->_cPtr,$x);
	}

	public function is_empty() {
		return StrVector_is_empty($this->_cPtr);
	}

	public function pop() {
		return StrVector_pop($this->_cPtr);
	}

	public function get($i) {
		return StrVector_get($this->_cPtr,$i);
	}

	public function set($i,$val) {
		StrVector_set($this->_cPtr,$i,$val);
	}
}

class SimpleQueryResult {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		$func = 'SimpleQueryResult_'.$var.'_set';
		if (function_exists($func)) return call_user_func($func,$this->_cPtr,$value);
		if ($var === 'thisown') return swig_libsimplequery_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __isset($var) {
		if (function_exists('SimpleQueryResult_'.$var.'_set')) return true;
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __get($var) {
		$func = 'SimpleQueryResult_'.$var.'_get';
		if (function_exists($func)) {
			$r = call_user_func($func,$this->_cPtr);
			if (!is_resource($r)) return $r;
			$c=substr(get_resource_type($r), (strpos(get_resource_type($r), '__') ? strpos(get_resource_type($r), '__') + 2 : 3));
			return new $c($r);
		}
		if ($var === 'thisown') return swig_libsimplequery_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	public function toString() {
		return SimpleQueryResult_toString($this->_cPtr);
	}

	public function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_SimpleQueryResult') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_SimpleQueryResult();
	}
}

class SimpleQueryRunner {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_libsimplequery_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_libsimplequery_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	public function __construct($_indexPath) {
		if (is_resource($_indexPath) && get_resource_type($_indexPath) === '_p_SimpleQueryRunner') {
			$this->_cPtr=$_indexPath;
			return;
		}
		$this->_cPtr=new_SimpleQueryRunner($_indexPath);
	}

	public function runAnnotatedQuery($query,$resultsRequested) {
		return SimpleQueryRunner_runAnnotatedQuery($this->_cPtr,$query,$resultsRequested);
	}
}


?>
