/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef PHP_LIBSIMPLEQUERY_H
#define PHP_LIBSIMPLEQUERY_H

extern zend_module_entry libsimplequery_module_entry;
#define phpext_libsimplequery_ptr &libsimplequery_module_entry

#ifdef PHP_WIN32
# define PHP_LIBSIMPLEQUERY_API __declspec(dllexport)
#else
# define PHP_LIBSIMPLEQUERY_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(libsimplequery);
PHP_MSHUTDOWN_FUNCTION(libsimplequery);
PHP_RINIT_FUNCTION(libsimplequery);
PHP_RSHUTDOWN_FUNCTION(libsimplequery);
PHP_MINFO_FUNCTION(libsimplequery);

ZEND_NAMED_FUNCTION(_wrap_new_StrVector);
ZEND_NAMED_FUNCTION(_wrap_StrVector_size);
ZEND_NAMED_FUNCTION(_wrap_StrVector_capacity);
ZEND_NAMED_FUNCTION(_wrap_StrVector_reserve);
ZEND_NAMED_FUNCTION(_wrap_StrVector_clear);
ZEND_NAMED_FUNCTION(_wrap_StrVector_push);
ZEND_NAMED_FUNCTION(_wrap_StrVector_is_empty);
ZEND_NAMED_FUNCTION(_wrap_StrVector_pop);
ZEND_NAMED_FUNCTION(_wrap_StrVector_get);
ZEND_NAMED_FUNCTION(_wrap_StrVector_set);
ZEND_NAMED_FUNCTION(_wrap_SimpleQueryResult_snippet_set);
ZEND_NAMED_FUNCTION(_wrap_SimpleQueryResult_snippet_get);
ZEND_NAMED_FUNCTION(_wrap_SimpleQueryResult_title_set);
ZEND_NAMED_FUNCTION(_wrap_SimpleQueryResult_title_get);
ZEND_NAMED_FUNCTION(_wrap_SimpleQueryResult_path_set);
ZEND_NAMED_FUNCTION(_wrap_SimpleQueryResult_path_get);
ZEND_NAMED_FUNCTION(_wrap_SimpleQueryResult_url_set);
ZEND_NAMED_FUNCTION(_wrap_SimpleQueryResult_url_get);
ZEND_NAMED_FUNCTION(_wrap_SimpleQueryResult_docno_set);
ZEND_NAMED_FUNCTION(_wrap_SimpleQueryResult_docno_get);
ZEND_NAMED_FUNCTION(_wrap_SimpleQueryResult_toString);
ZEND_NAMED_FUNCTION(_wrap_new_SimpleQueryResult);
ZEND_NAMED_FUNCTION(_wrap_new_SimpleQueryRunner);
ZEND_NAMED_FUNCTION(_wrap_SimpleQueryRunner_runAnnotatedQuery);
#endif /* PHP_LIBSIMPLEQUERY_H */
