/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef PHP_SIMPLEQUERY_H
#define PHP_SIMPLEQUERY_H

extern zend_module_entry simplequery_module_entry;
#define phpext_simplequery_ptr &simplequery_module_entry

#ifdef PHP_WIN32
# define PHP_SIMPLEQUERY_API __declspec(dllexport)
#else
# define PHP_SIMPLEQUERY_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(simplequery);
PHP_MSHUTDOWN_FUNCTION(simplequery);
PHP_RINIT_FUNCTION(simplequery);
PHP_RSHUTDOWN_FUNCTION(simplequery);
PHP_MINFO_FUNCTION(simplequery);

ZEND_NAMED_FUNCTION(_wrap_new_StringVector);
ZEND_NAMED_FUNCTION(_wrap_StringVector_size);
ZEND_NAMED_FUNCTION(_wrap_StringVector_capacity);
ZEND_NAMED_FUNCTION(_wrap_StringVector_reserve);
ZEND_NAMED_FUNCTION(_wrap_StringVector_clear);
ZEND_NAMED_FUNCTION(_wrap_StringVector_push);
ZEND_NAMED_FUNCTION(_wrap_StringVector_is_empty);
ZEND_NAMED_FUNCTION(_wrap_StringVector_pop);
ZEND_NAMED_FUNCTION(_wrap_StringVector_get);
ZEND_NAMED_FUNCTION(_wrap_StringVector_set);
ZEND_NAMED_FUNCTION(_wrap_SimpleQueryResult_snippet_set);
ZEND_NAMED_FUNCTION(_wrap_SimpleQueryResult_snippet_get);
ZEND_NAMED_FUNCTION(_wrap_SimpleQueryResult_title_set);
ZEND_NAMED_FUNCTION(_wrap_SimpleQueryResult_title_get);
ZEND_NAMED_FUNCTION(_wrap_SimpleQueryResult_path_set);
ZEND_NAMED_FUNCTION(_wrap_SimpleQueryResult_path_get);
ZEND_NAMED_FUNCTION(_wrap_SimpleQueryResult_url_set);
ZEND_NAMED_FUNCTION(_wrap_SimpleQueryResult_url_get);
ZEND_NAMED_FUNCTION(_wrap_SimpleQueryResult_docno_set);
ZEND_NAMED_FUNCTION(_wrap_SimpleQueryResult_docno_get);
ZEND_NAMED_FUNCTION(_wrap_SimpleQueryResult_toString);
ZEND_NAMED_FUNCTION(_wrap_new_SimpleQueryResult);
ZEND_NAMED_FUNCTION(_wrap_new_SimpleQueryRunner);
ZEND_NAMED_FUNCTION(_wrap_SimpleQueryRunner_runAnnotatedQuery);
#endif /* PHP_SIMPLEQUERY_H */
