
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_weblib_linguist_Humor__
#define __com_weblib_linguist_Humor__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace com
  {
    namespace weblib
    {
      namespace linguist
      {
          class Humor;
      }
    }
  }
}

class com::weblib::linguist::Humor : public ::java::lang::Object
{

public:
  static void initialize(::java::lang::String *, jint);
  static jboolean isInitialized();
  static jint closeMorph(jint);
  static jint closeStemming();
  static jint closeWordGenerating();
  static jint closeWordFormsGenerating();
  static JArray< ::java::lang::String * > * getStem(::java::lang::String *);
  static JArray< ::java::lang::String * > * getAnalyze(::java::lang::String *);
  static JArray< ::java::lang::String * > * getWordGenerate(::java::lang::String *);
  static JArray< ::java::lang::String * > * getWordForms(::java::lang::String *, jint);
  static JArray< ::java::lang::String * > * getSyns(::java::lang::String *, jint);
  static void TestError(::java::lang::String *, jint);
private:
  Humor();
  static jint init(::java::lang::String *, jint, jint);
  static jint close(jint);
  static JArray< ::java::lang::String * > * stem(jint, ::java::lang::String *);
  static JArray< ::java::lang::String * > * analyze(jint, ::java::lang::String *);
  static JArray< ::java::lang::String * > * generate(jint, ::java::lang::String *);
  static JArray< ::java::lang::String * > * generateWordForms(jint, ::java::lang::String *, jint);
  static JArray< ::java::lang::String * > * getSynonims(jint, ::java::lang::String *, jint);
public:
  static void main(JArray< ::java::lang::String * > *);
private:
  static jint _stemmingId;
  static jint _generateId;
  static jint _generateWFormsId;
  static jboolean _initialized;
public:
  static ::java::lang::Class class$;
};

#endif // __com_weblib_linguist_Humor__
